### ISSUE TITLE
Request to provide an example of the additions file

### ISSUE THREAD

**Issue by verdurin** [fizwit/easy_update#10]
It would be helpful if you could provide an example of the `--add` command.
I have tried it and while with `--verbose` I can see that `easy_update` is detecting the extra extensions, it does not in fact add them to the `easyconfig`.

**Comment by fizwit** [comment]
I have removed -add as a feature. If you are creating a new bundle (or adding to an existing bundle) you can add lines like this to you Easyconfig with blank version strings.   easy_update will add the dependencies and fill in the version information. 

...
exts_defaultclass = 'RPackage'
exts_list = [
    ('CARBayes', '')
]
...
