### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by ponomarevsy** [fizwit/easy_update#6]
Hello,

This error most likely the result of the updated bioconda directory structure:

» ./easy_update.py R-3.4.0-goolf-1.7.20.eb                        
  File "./easy_update.py", line 286
    '%s/data/experiment/packages.json' % (base_path, biocver)]
                                     ^
**SyntaxError: invalid syntax**

Looking inside file "./easy_update.py", line 286:
```
def read_bioconductor_pacakges(self):
        """ read the Bioconductor package list into bio_data dict
        """
        base_path = 'https://bioconductor.org/packages/json/'
        bioc_urls = ['%s/bioc/packages.json' % (base_path, biocver),
                     '%s/data/annotation/packages.json' % (base_path, biocver,)
                     '%s/data/experiment/packages.json' % (base_path, biocver)]
        self.bioc_data = {}
        for url in bioc_urls:
            try:
                response = urllib2.urlopen(url)
            except IOError as e:
                print 'URL request: ', url
                sys.exit(e)
...
```
What would the correct (new) bioconda path should be? Thank you in advance!

**Comment by ponomarevsy** [comment]
Ok, I've made some progress here, but now getting a different error:

    def read_bioconductor_pacakges(self):
        """ read the Bioconductor package list into bio_data dict
        """
        base_path = "**https://bioconductor.org/packages/release**"
        #bioc_urls = ['%s/bioc/packages.json' % (base_path, biocver),
        #             '%s/data/annotation/packages.json' % (base_path, biocver,)
        #             '%s/data/experiment/packages.json' % (base_path, biocver)]

        bioc_urls = ["%s/**BiocViews.html#___Software/packages.json**" % (base_path, biocver),
                     "%s/**BiocViews.html#___AnnotationData/packages.json**" % (base_path, biocver)**,**
                     "%s/**BiocViews.html#___ExperimentData/packages.json**" % (base_path, biocver)]
        self.bioc_data = {}
        for url in bioc_urls:
            try:
                response = urllib2.urlopen(url)

» ./easy_update.py R-3.4.0-goolf-1.7.20.eb --verbose
Traceback (most recent call last):
  File "./easy_update.py", line 502, in <module>
    module = R(sys.argv[1], add_packages, package, verbose=vflag)
**TypeError: __init__() got multiple values for keyword argument 'verbose'**

**Comment by fizwit** [comment]
I need to push a new version.  The path versions for Biocondutor have been updated.

**Comment by ponomarevsy** [comment]
And that will happen when???

**Comment by fizwit** [comment]
uploaded new version, much improved please tryit.
