### ISSUE TITLE
Error with Python version support

### ISSUE THREAD

**Issue by verdurin** [fizwit/easy_update#8]
Even when the Python version is specified as a parameter, this does not appear to be processed for the output filename:
```
./easy_update.py --pyver 2.7 ~/R-3.5.2-foss-2018b-Python-2.7.15.eb
Warning: file name does not match easybuild module name
 file name: R-3.5.2-foss-2018b-Python-2.7.15, module name: R-3.5.2-foss-2018b-Python-%(pyver)s
Writing output to: R-3.5.2-foss-2018b-Python-%(pyver)s.update
BioCondutor verserion: biocver not set
No action: base
No action: datasets
No action: graphics
No action: grDevices
No action: grid
No action: methods
No action: splines
No action: stats
No action: stats4
No action: tools
No action: utils
Duplicate: pkgconfig
Duplicate: numDeriv
Duplicate: gridExtra
Duplicate: xfun
Duplicate: callr
Duplicate: ucminf
Duplicate: ordinal
Duplicate: clipr
Duplicate: later
Duplicate: promises
Duplicate: bibtex
Duplicate: gbRd
Duplicate: Rdpack
Duplicate: NMF
Updated Packages: 242
New Packages: 25
Dropped Packages: 14
```

**Comment by fizwit** [comment]
easy_update only works in a single mode.  It can update R or Python, but not both at the same time. From your example, only the R packages would be updated.  You would have to update the Python dependency separately from its base easyconfig file. The erroneous biocver not set message has been fixed. Version 2.0 interpolates %(pyver) and %(rver)s correctly now. 

thanks for your feedback with easy_update.  Today's commit has the new feature you requested.
